#!/bin/sh

# Usage: checkrelocs <objs.o> [...]

# This script checks for any outstanding relocations in the
# .text.preload and .text.irq sections.  Since these sections are
# moved to new areas in memory during the haret runtime, the code can
# not reliably access other parts of the haret system.  (Having an
# external relocation will result in a mysterious runtime error.)

LD=$BASE/bin/arm-mingw32ce-ld
OBJDUMP=$BASE/bin/arm-mingw32ce-objdump
TMP=tmp_link.o
IGNORE=" ARM_26D | ARM_32[ ]*\.text\+"

$LD -r "$@" -o $TMP
$OBJDUMP -C -r -j .text.preload -j .text.irq $TMP | egrep -v "$IGNORE" | grep -q '^0'
STATUS=$?

if [ $STATUS != 0 ]; then
    rm -f $TMP
    exit 0
fi

echo "ERROR:"
echo "ERROR: There is an external reference from a standalone haret section."
echo "ERROR:"

$OBJDUMP -C -r -j .text.preload -j .text.irq $TMP | egrep -v "$IGNORE"
rm -f $TMP

exit 1
